#!/usr/bin/env python3
"""Token-Efficient Blender 3D Scene Pipeline.

Provides headless scene generation, rendering, inspection, and export
with minimal token overhead for autonomous agent workflows.
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

BLENDER_BIN = "/usr/bin/blender"

BOILERPLATE_SCENE_TEMPLATE = """\"\"\"Autogenerated Blender Scene Script.\"\"\"
import bpy
import math

# Reset scene
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene

# Configure rendering engine & color management
scene.render.engine = 'BLENDER_EEVEE_NEXT' if hasattr(bpy.app, 'version') and bpy.app.version >= (4, 2, 0) else 'BLENDER_EEVEE'
if hasattr(scene.eevee, 'use_gtao'):
    scene.eevee.use_gtao = True
if hasattr(scene.eevee, 'use_bloom'):
    scene.eevee.use_bloom = True
if hasattr(scene.eevee, 'use_ssr'):
    scene.eevee.use_ssr = True

scene.view_settings.view_transform = 'AgX' if 'AgX' in bpy.types.ColorManagedViewSettings.bl_rna.properties['view_transform'].enum_items else 'Filmic'
scene.view_settings.look = 'Medium High Contrast'

# Camera setup
cam_data = bpy.data.cameras.new("MainCamera")
cam_data.lens = 50
cam_obj = bpy.data.objects.new("MainCamera", cam_data)
scene.collection.objects.link(cam_obj)
scene.camera = cam_obj
cam_obj.location = (0.0, -8.0, 3.5)
cam_obj.rotation_euler = (math.radians(70), 0, 0)

# Lighting rig
sun_data = bpy.data.lights.new("SunLight", type='SUN')
sun_data.energy = 3.5
sun_data.color = (1.0, 0.95, 0.9)
sun_obj = bpy.data.objects.new("SunLight", sun_data)
scene.collection.objects.link(sun_obj)
sun_obj.rotation_euler = (math.radians(45), math.radians(30), math.radians(-30))

rim_data = bpy.data.lights.new("RimLight", type='POINT')
rim_data.energy = 50.0
rim_data.color = (0.4, 0.7, 1.0)
rim_obj = bpy.data.objects.new("RimLight", rim_data)
scene.collection.objects.link(rim_obj)
rim_obj.location = (3.0, 4.0, 4.0)

# Environment world lighting
world = bpy.data.worlds.new("World")
scene.world = world
world.use_nodes = True
bg_node = world.node_tree.nodes.get("Background")
if bg_node:
    bg_node.inputs[0].default_value = (0.05, 0.05, 0.08, 1.0)
    bg_node.inputs[1].default_value = 0.8

# Ground Plane with basic PBR material
bpy.ops.mesh.primitive_plane_add(size=20, location=(0, 0, 0))
ground = bpy.context.active_object
ground.name = "Ground"

ground_mat = bpy.data.materials.new(name="GroundMaterial")
ground_mat.use_nodes = True
bsdf = ground_mat.node_tree.nodes.get("Principled BSDF")
if bsdf:
    bsdf.inputs["Base Color"].default_value = (0.12, 0.12, 0.14, 1.0)
    bsdf.inputs["Roughness"].default_value = 0.25
    bsdf.inputs["Metallic"].default_value = 0.1
ground.data.materials.append(ground_mat)

# User scene geometry starts below:
"""

INSPECT_SCRIPT = """import bpy, json

data = {
    "objects": [],
    "lights": [],
    "cameras": [],
    "total_vertices": 0
}

for obj in bpy.context.scene.objects:
    item = {
        "name": obj.name,
        "type": obj.type,
        "location": [round(v, 2) for v in obj.location],
        "rotation": [round(v, 2) for v in obj.rotation_euler],
    }
    if obj.type == 'MESH' and obj.data:
        verts = len(obj.data.vertices)
        item["vertices"] = verts
        data["total_vertices"] += verts
        item["materials"] = [m.name for m in obj.data.materials if m]
        data["objects"].append(item)
    elif obj.type == 'LIGHT' and obj.data:
        item["light_type"] = obj.data.type
        item["intensity"] = round(obj.data.energy, 2)
        data["lights"].append(item)
    elif obj.type == 'CAMERA' and obj.data:
        item["lens"] = obj.data.lens
        data["cameras"].append(item)

print("---SCENE_INSPECT_JSON---")
print(json.dumps(data, indent=2))
"""

def run_blender_script(script_path: Path, output_image: Path = None, output_blend: Path = None, output_glb: Path = None, res: int = 512) -> tuple[bool, str]:
    """Execute a python script in headless blender, optionally rendering and exporting."""
    wrapper_path = script_path.parent / f"_runner_{script_path.name}"
    
    wrapper_lines = [
        "import bpy",
        f"with open(r'{script_path}', 'r') as f: exec(f.read())"
    ]
    
    if output_image:
        wrapper_lines.append(f"""
scene = bpy.context.scene
scene.render.image_settings.file_format = 'PNG'
scene.render.filepath = r'{output_image}'
scene.render.resolution_x = {res}
scene.render.resolution_y = {res}
bpy.ops.render.render(write_still=True)
print(f"RENDER_SAVED: {output_image}")
""")
        
    if output_blend:
        wrapper_lines.append(f"""
bpy.ops.wm.save_as_mainfile(filepath=r'{output_blend}')
print(f"BLEND_SAVED: {output_blend}")
""")

    if output_glb:
        wrapper_lines.append(f"""
bpy.ops.export_scene.gltf(filepath=r'{output_glb}', export_format='GLB')
print(f"GLB_SAVED: {output_glb}")
""")

    wrapper_path.write_text("\n".join(wrapper_lines), encoding="utf-8")

    cmd = [BLENDER_BIN, "--background", "--python", str(wrapper_path)]
    try:
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=120)
        wrapper_path.unlink(missing_ok=True)
        if proc.returncode != 0 or "Traceback (most recent call last):" in proc.stdout or "Traceback (most recent call last):" in proc.stderr:
            err_msg = proc.stderr if proc.stderr else proc.stdout
            return False, err_msg
        return True, proc.stdout
    except Exception as e:
        wrapper_path.unlink(missing_ok=True)
        return False, str(e)

def inspect_scene(script_path: Path) -> dict:
    """Run inspection on the scene defined by the script."""
    wrapper_path = script_path.parent / f"_inspect_{script_path.name}"
    wrapper_code = f"""
with open(r'{script_path}', 'r') as f: exec(f.read())
{INSPECT_SCRIPT}
"""
    wrapper_path.write_text(wrapper_code, encoding="utf-8")
    cmd = [BLENDER_BIN, "--background", "--python", str(wrapper_path)]
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=60)
    wrapper_path.unlink(missing_ok=True)
    
    if "---SCENE_INSPECT_JSON---" in proc.stdout:
        raw = proc.stdout.split("---SCENE_INSPECT_JSON---")[1]
        start = raw.find("{")
        end = raw.rfind("}")
        if start != -1 and end != -1:
            try:
                return json.loads(raw[start:end+1])
            except Exception:
                pass
    return {"error": "Failed to parse scene inspect", "output": proc.stdout}

def get_critic_prompt(concept_img: str, render_img: str, round_num: int = 1, prior_verdict: str = "") -> str:
    """Format token-minimal prompt for subagent critic."""
    prior_sec = f"Prior Directives:\n{prior_verdict}\n" if prior_verdict else ""
    return f"""You are the Art Director Critic reviewing a 3D real-time render against the target concept.
Round: {round_num}

Images to compare:
1. Target Concept: {concept_img}
2. Current Render: {render_img}

Evaluation Rubric (Strict Gated Ladder):
- Tier 1 (0-3): Layout, camera framing, scale & positioning of major elements.
- Tier 2 (3-5): Key lighting direction, contrast, shadow depth, color palette, atmosphere.
- Tier 3 (5-7): Materials & surfaces (roughness, metallic, wetness, normal depth). No flat plastic.
- Tier 4 (7-9): Fine details, bevels, secondary clutter, micro-textures.
- Tier 5 (9-10): Indistinguishable match.

{prior_sec}
Output strictly in this format:
SCORE: <float 0-10>
TIER: <Tier 1-5>
STATUS: <PASS if score >= 7.5 else ITERATE>
BLOCKERS:
- <Specific actionable failure 1 with exact fix>
- <Specific actionable failure 2 with exact fix>
- <Specific actionable failure 3 with exact fix>
"""

def main():
    parser = argparse.ArgumentParser(description="Token-efficient 3D Blender pipeline")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Init
    init_parser = subparsers.add_parser("init", help="Initialize scene directory and base script")
    init_parser.add_argument("--dir", default=".3d-scene", help="Scene output directory")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing scene.py")

    # Render
    render_parser = subparsers.add_parser("render", help="Render script to image and export blend/glb")
    render_parser.add_argument("--script", required=True, help="Path to scene python script")
    render_parser.add_argument("--out-img", help="Path to output render PNG")
    render_parser.add_argument("--out-blend", help="Path to output .blend file")
    render_parser.add_argument("--out-glb", help="Path to output .glb file")
    render_parser.add_argument("--res", type=int, default=512, help="Resolution (default 512 for fast loop)")

    # Inspect
    inspect_parser = subparsers.add_parser("inspect", help="Inspect scene geometry, lights, camera in concise JSON")
    inspect_parser.add_argument("--script", required=True, help="Path to scene python script")

    # Critic prompt
    critic_parser = subparsers.add_parser("critic-prompt", help="Generate minimal prompt for subagent critic")
    critic_parser.add_argument("--concept", required=True, help="Path to target concept image")
    critic_parser.add_argument("--render", required=True, help="Path to current render image")
    critic_parser.add_argument("--round", type=int, default=1, help="Round number")
    critic_parser.add_argument("--prior", default="", help="Prior round verdict")

    args = parser.parse_args()

    if args.command == "init":
        scene_dir = Path(args.dir).resolve()
        scene_dir.mkdir(parents=True, exist_ok=True)
        script_file = scene_dir / "scene.py"
        if script_file.exists() and not args.force:
            print(f"Error: {script_file} already exists. Use --force to overwrite.", file=sys.stderr)
            sys.exit(1)
        script_file.write_text(BOILERPLATE_SCENE_TEMPLATE, encoding="utf-8")
        print(f"Initialized scene scaffold at: {script_file}")

    elif args.command == "render":
        script_path = Path(args.script).resolve()
        if not script_path.is_file():
            print(f"Error: script not found: {script_path}", file=sys.stderr)
            sys.exit(1)
        out_img = Path(args.out_img).resolve() if args.out_img else None
        out_blend = Path(args.out_blend).resolve() if args.out_blend else None
        out_glb = Path(args.out_glb).resolve() if args.out_glb else None
        
        success, out = run_blender_script(script_path, out_img, out_blend, out_glb, args.res)
        if not success:
            print(f"FAILED:\n{out}", file=sys.stderr)
            sys.exit(1)
        print("SUCCESS")
        if out_img:
            print(f"IMAGE: {out_img}")
        if out_blend:
            print(f"BLEND: {out_blend}")
        if out_glb:
            print(f"GLB: {out_glb}")

    elif args.command == "inspect":
        script_path = Path(args.script).resolve()
        if not script_path.is_file():
            print(f"Error: script not found: {script_path}", file=sys.stderr)
            sys.exit(1)
        data = inspect_scene(script_path)
        print(json.dumps(data, indent=2))

    elif args.command == "critic-prompt":
        prompt = get_critic_prompt(args.concept, args.render, args.round, args.prior)
        print(prompt)

if __name__ == "__main__":
    main()
